### ISSUE TITLE
display_CenterOut.py does not work because missing ~/.DISPLAY file.

### ISSUE THREAD

**Issue by cboulay** [brandbci/brand-tutorial#3]
display_CenterOut.py assumes there is a `~/.DISPLAY` file on the system. If there isn't, this node doesn't get built because sys.exit(1) is called when the module is imported by Cython.

I suggest the following changes.

1. For users like me who already have a `DISPLAY` environment variable, the `try` block can be rewritten as:

```
try:
    if "DISPLAY" not in os.environ:
        with open(os.path.join(os.path.expanduser('~'), '.DISPLAY'), 'r') as f:
            os.environ["DISPLAY"] = f.read().splitlines()[0]
```

2. For everyone else, there should be instructions in 00_setup.md to create the ~/.DISPLAY file or otherwise set the [DISPLAY environment variable](https://help.ubuntu.com/community/EnvironmentVariables#graphical-desktop-related-variables)

**Comment by yahiaali** [comment]
Thanks for pointing this out @cboulay. This issue is now fixed with commit https://github.com/brandbci/brand-tutorial/commit/0c46e724e2add10c6a249db207e227c0a6f6dd98, which skips looking for the `~/.DISPLAY` file if the `DISPLAY` variable is already set, and commit https://github.com/brandbci/brand-tutorial/commit/e03ac861ee52279a17b796b0053c4b33796c33ff, which adds instructions for creating the `~/.DISPLAY` file.
